% -------------------------------------------------------------------
%  Generated by MATLAB on 26-Apr-2020 12:48:47
%  MATLAB version: 9.7.0.1296695 (R2019b) Update 4
% -------------------------------------------------------------------
saveVarsMat = load('scan2d_greentest.mat');

scandata2 = saveVarsMat.scandata2; % <1x1 ros.msg.sensor_msgs.LaserScan> unsupported class

clear saveVarsMat;
